# Generated by Django 5.0 on 2023-12-18 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=255)),
                ('description', models.TextField(null=True)),
                ('file_name', models.CharField(max_length=255, null=True)),
                ('file_extension', models.CharField(max_length=30, null=True)),
                ('file_type', models.CharField(max_length=30, null=True)),
                ('file_size', models.CharField(max_length=255, null=True)),
                ('file_path', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('file_status', models.IntegerField(choices=[(1, 'active'), (0, 'inactive')], default=1)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
