# Generated by Django 5.0 on 2023-12-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_mediaupload_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaupload',
            name='file_type',
            field=models.TextField(null=True),
        ),
    ]
